jta:
  atomikos:
    datasource:
      one:
#        unique-resource-name: oneDataSource
#        xaDataSourceClassName: com.alibaba.druid.pool.xa.DruidXADataSource
#        max-pool-size: 25
#        min-pool-size: 3
#        xa-properties:
#          driverClassName: com.mysql.cj.jdbc.Driver #高版本
#          #driverClassName: com.mysql.jdbc.Driver #低版本
#          username: qd_issue
#          password: qd_issue
#          url: jdbc:mysql://127.0.0.1:3306/qd_issue?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false

        name: oneDataSource
        url: jdbc:mysql://127.0.0.1:3306/qd_issue?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
        username: qd_issue
        password: qd_issue
        driver-class-name: com.mysql.cj.jdbc.Driver
        ###################以下为druid增加的配置###########################
        #type: com.alibaba.druid.pool.xa.DruidXADataSource
        # 下面为连接池的补充设置，应用到上面所有数据源中
        # 初始化大小，最小，最大
        initialSize: 5
        minIdle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        # 合并多个DruidDataSource的监控数据
        useGlobalDataSourceStat: true

      two:
#        unique-resource-name: twoDataSource
#        xaDataSourceClassName: com.alibaba.druid.pool.xa.DruidXADataSource
#        max-pool-size: 25
#        min-pool-size: 3
#        xa-properties:
#          driverClassName: com.mysql.cj.jdbc.Driver #高版本
#          #driverClassName: com.mysql.jdbc.Driver #低版本
#          username: di
#          password: di
#          url: jdbc:mysql://127.0.0.1:3306/di?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
        name: twoDataSource
        url: jdbc:mysql://127.0.0.1:3306/di?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
        username: di
        password: di
        driver-class-name: com.mysql.cj.jdbc.Driver
        ###################以下为druid增加的配置###########################
        #type: com.alibaba.druid.pool.xa.DruidXADataSource
        # 下面为连接池的补充设置，应用到上面所有数据源中
        # 初始化大小，最小，最大
        initialSize: 5
        minIdle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        # 合并多个DruidDataSource的监控数据
        useGlobalDataSourceStat: true

logging:
  level:
    com.zoolon: debug
  file: /issue-logs/log.txt

# JWT
jwt:
  tokenHeader: Authorization
  secret: mySecret
  authTokenStart: "Bearer "
  expiration: 604800
